---
title: "NAMCS Pemphigus and Pemphigoid"
author: "Dom"
date: "11/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = '/Volumes/GoogleDrive/My Drive/20181101_NAMCS Pierce', echo = TRUE)
```

#R packages used in program
```{r message = FALSE}
library(dplyr)

#package to load Stata datasets into R
library(haven)
library(Hmisc)

#package to replace missing indicator value with NA
library(naniar)
```

#Import NAMCS datasets from Stata format
```{r load}
setwd("/Volumes/GoogleDrive/My Drive/20181101_NAMCS Pierce/Datasets/!NAMCS_Stata")

#read in the stata dataset
bigdata <- read_dta("namcs2015.dta")

#list the NAMCS variables that are relevant to analysis
keepvars <- c("YEAR", "SETTYPE", "PATWT", "SEX", "AGE", "AGER", 
              "DIAG1", "DIAG2", "DIAG3", "dx_pemphs", "dx_pemphd",
              "RACER", "RACERETH", "PAYTYPER", "REGIONOFF", "MSA", "OWNSR", "SPECCAT", 
              "MED1", "MED2", "MED3", "MED4", "MED5", "MED6", "MED7", "MED8", "MED9", "MED10", 
              "MED11", "MED12", "MED13", "MED14", "MED15", "MED16", "MED17", "MED18", "MED19", "MED20", 
              "MED21", "MED22", "MED23", "MED24", "MED25", "MED26", "MED27", "MED28", "MED29", "MED30"
              )

#identify the variables where diagnosis codes exist
dxvars <- bigdata[c("DIAG1", "DIAG2", "DIAG3")]

#make logical variable of whether observations diagnosed with:
  #pemphigus diagnosis
    bigdata$dx_pemphs <- sapply(dxvars, grepl, pattern = "6944")
  #pemphigoid diagnosis
    bigdata$dx_pemphd <- sapply(dxvars, grepl, pattern = "6945")

#use sapply to put grepl over multiple column variables
newdata <- subset(bigdata, dx_pemphs | dx_pemphd, select = keepvars)
#newdata3 <- bigdata %>% filter(DIAG1 == )
glimpse(newdata)
```
